version: '3.9'

services:
  api_db:
    image: postgres:13
    container_name: api_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: opportunities_db
    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql

  api_app:
    build: .
    container_name: api_app
    depends_on:
      - api_db
    environment:
      DB_HOST: api_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: opportunities_db
    ports:
      - "8000:8000"
    command: ["./app"]

volumes:
  db_data: