services:
  api_db:
    image: postgres:13
    container_name: api_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql

  api_app:
    build: .
    container_name: api_app
    depends_on:
      - api_db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    command: ["./app"]

volumes:
  db_data: